import { NextResponse } from "next/server";
import { GoogleGenAI } from "@google/genai";

// Initialize the Google Gen AI SDK
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });

export async function POST(request: Request) {
  try {
    const { prompt, theme } = await request.json();

    if (!prompt) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    // Enhance prompt based on the theme to get better results from Imagen 3
    let enhancedPrompt = `A high-quality, vibrant illustration. No text in the image. `;
    
    if (theme === "space") {
      enhancedPrompt += `Theme: Outer space adventure. Beautiful cosmic background with stars and galaxies. `;
    } else if (theme === "ocean") {
      enhancedPrompt += `Theme: Underwater ocean world. Colorful corals, clear blue water, beautiful marine life. `;
    } else if (theme === "forest") {
      enhancedPrompt += `Theme: Magical fantasy forest. Glowing mushrooms, giant ancient trees, fairy lights. `;
    } else if (theme === "city") {
      enhancedPrompt += `Theme: Futuristic sci-fi city. Neon lights, flying cars, advanced technology, bright and optimistic. `;
    }

    if (prompt.includes("인물이 전혀 등장하지 않는")) {
      enhancedPrompt += `User's idea: ${prompt}. IMPORTANT: Draw a pure landscape with absolutely NO humans, NO people, NO characters, NO animals. Empty scenery only.`;
    } else {
      enhancedPrompt += `User's idea: ${prompt}. The composition should leave space in the center-bottom for a person to be inserted later.`;
    }

    console.log("Generating image with prompt:", enhancedPrompt);

    // Call generateContent with the gemini-3.1-flash-image-preview model (Nano Banana)
    // Note: If you want to use the Pro model, change this to "gemini-3-pro-image-preview"
    const response = await ai.models.generateContent({
      model: "gemini-3.1-flash-image-preview",
      contents: enhancedPrompt,
    });

    let base64Image = null;
    
    // Find the inlineData part that contains the image
    const parts = response.candidates?.[0]?.content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        base64Image = part.inlineData.data;
        break;
      }
    }

    if (!base64Image) {
      throw new Error("No image generated by the model");
    }
    
    return NextResponse.json({ 
      success: true, 
      image: `data:image/jpeg;base64,${base64Image}` 
    });

  } catch (error: any) {
    console.error("Error generating image:", error);
    return NextResponse.json(
      { error: error.message || "Failed to generate image" },
      { status: 500 }
    );
  }
}
